name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello
        rum: echo "Hellow World"
      - name: print bye
        run: echo "Bye World"
